#!/bin/bash

echo "My name is $1"
echo "My home directory is $2"
echo "My favourite color is $3"
                                                                                                            
echo $#                                                                                                            
                                                                                                            
                                                                                                           
                                                                                                            
                                                                                                            
                                                                                         
                                                                      
                                                                                                           
                                                                                                            
                                                                                                            
                                                                                                            
                                                                                                            
                                                                                                           
                                                                                                            
                                                                                                            
                                                                                                           
                                                                                                                                                                      
